local_backend: true

backend:
  name: git-gateway
  branch: main
  # base_url: https://theburrellconnection.com # optional for custom deploy/auth hosts

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "About Page"
    name: "aboutPage"
    files:
      - label: "About Page"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

  - label: "Contact Page"
    name: "contactPage"
    files:
      - label: "Contact Page"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "releases"
    label: "Releases"
    folder: "src/content/releases"
    create: true
    slug: "{{slug}}"
    preview_path: "releases/{{slug}}/"
    format: "yaml-frontmatter"

    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "artist", label: "Artist", widget: "string" }
      - {
          name: "artistLink",
          label: "Artist Link",
          widget: "string",
          required: false,
        }
      - {
          name: "otherArtists",
          label: "Other Artists",
          widget: "list",
          field: { name: "artist", label: "Artist", widget: "string" },
        }

      - { name: "releaseDate", label: "Release Date", widget: "datetime" }

      - { name: "cover", label: "Cover", widget: "image" }
      - name: "gallery"
        label: "Gallery"
        widget: "list"
        field: { name: "image", label: "Image", widget: "image" }
        required: false

      - { name: "description", label: "Description", widget: "text" }
      - { name: "credits", label: "Credits", widget: "text", required: false }
      - {
          name: "masteredBy",
          label: "Mastered By",
          widget: "string",
          required: false,
        }
      - { name: "label", label: "Label", widget: "string", required: false }
      - {
          name: "labelLink",
          label: "Label Link",
          widget: "string",
          required: false,
        }

      - name: "genre"
        label: "Genre"
        widget: "list"
        field: { name: "genre", label: "Genre", widget: "string" }
        default: []
        required: false

      - name: "format"
        label: "Format"
        widget: "select"
        options: ["vinyl", "digital", "cassette", "CD", "other"]
        default: "digital"

      - { name: "isDraft", label: "Draft", widget: "boolean", default: false }
      - {
          name: "isUpcoming",
          label: "Upcoming",
          widget: "boolean",
          default: false,
        }

      - {
          name: "pressKitLink",
          label: "Press Kit URL",
          widget: "string",
          required: false,
        }

      - name: "links"
        label: "Streaming & Purchase Links"
        widget: "object"
        fields:
          - {
              name: "bandcamp",
              label: "Bandcamp",
              widget: "string",
              required: false,
            }
          - {
              name: "spotify",
              label: "Spotify",
              widget: "string",
              required: false,
            }
          - {
              name: "soundcloud",
              label: "SoundCloud",
              widget: "string",
              required: false,
            }
          - {
              name: "appleMusic",
              label: "Apple Music",
              widget: "string",
              required: false,
            }
          - {
              name: "youtube",
              label: "YouTube",
              widget: "string",
              required: false,
            }
          - { name: "tidal", label: "Tidal", widget: "string", required: false }
          - {
              name: "discogs",
              label: "Discogs",
              widget: "string",
              required: false,
            }

      - name: "tags"
        label: "Tags"
        widget: "list"
        field: { name: "tag", label: "Tag", widget: "string" }
        required: false

      - { name: "body", label: "Body", widget: "markdown", required: false } # Optional Markdown body

  - name: "mixes"
    label: "DJ Mixes"
    folder: "src/content/mixes"
    format: "frontmatter"
    extension: "md"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "DJ", name: "dj", widget: "string" }
      - { label: "DJ Link", name: "djLink", widget: "string", required: false }
      - {
          label: "Other DJs",
          name: "otherDJs",
          widget: "list",
          required: false,
          default: [],
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
          media_library:
            {
              allow_multiple: false,
              config: { public_folder: "/", media_folder: "/" },
            },
        }

      - { label: "Event", name: "event", widget: "string", required: false }
      - {
          label: "Event Link",
          name: "eventLink",
          widget: "string",
          required: false,
        }
      - { label: "Venue", name: "venue", widget: "string", required: false }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          required: false,
        }

      - {
          label: "Is Draft",
          name: "isDraft",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Is Upcoming",
          name: "isUpcoming",
          widget: "boolean",
          default: false,
        }

      - label: "Links"
        name: "links"
        widget: "object"
        fields:
          - {
              label: "SoundCloud",
              name: "soundcloud",
              widget: "string",
              required: false,
            }
          - {
              label: "Mixcloud",
              name: "mixcloud",
              widget: "string",
              required: false,
            }
          - {
              label: "YouTube",
              name: "youtube",
              widget: "string",
              required: false,
            }
          - {
              label: "Bandcamp",
              name: "bandcamp",
              widget: "string",
              required: false,
            }
          - {
              label: "Download",
              name: "download",
              widget: "string",
              required: false,
            }
