local_backend: true

backend:
  name: git-gateway
  branch: main
  # base_url: https://theburrellconnection.com # optional for custom deploy/auth hosts

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "cover"
        label: "Cover Image"
        widget: "image"
        required: false
      - name: "coverAlt"
        label: "Cover Alt Text"
        widget: "string"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "slug"
        label: "Slug"
        widget: "string"
      - name: "snippet"
        label: "Snippet"
        widget: "text"
      - name: "category"
        label: "Category"
        widget: "string"
      - name: "pubDate"
        label: "Publication Date"
        widget: "datetime"
      - name: "isDraft"
        label: "Draft?"
        widget: "boolean"
        default: false
      - name: "updatedDate"
        label: "Updated Date"
        widget: "datetime"
        required: false
      - name: "author"
        label: "Author"
        widget: "string"
        default: "Retro Rocket Team"
      - name: "relatedArticles"
        label: "Related Articles"
        widget: "relation"
        collection: "articles"
        search_fields: ["title"]
        value_field: "slug"
        display_fields: ["title"]
        multiple: true
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
  - name: "releases"
    label: "Releases"
    folder: "src/content/releases"
    create: true
    slug: "{{slug}}"
    preview_path: "releases/{{slug}}/"
    format: "yaml-frontmatter"

    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "artist", label: "Artist", widget: "string" }
      - { name: "releaseDate", label: "Release Date", widget: "datetime" }

      - { name: "cover", label: "Cover", widget: "image" }
      - name: "gallery"
        label: "Gallery"
        widget: "list"
        field: { name: "image", label: "Image", widget: "image" }
        required: false

      - { name: "description", label: "Description", widget: "text" }
      - { name: "credits", label: "Credits", widget: "text", required: false }
      - {
          name: "masteredBy",
          label: "Mastered By",
          widget: "string",
          required: false,
        }
      - { name: "label", label: "Label", widget: "string", required: false }

      - name: "genre"
        label: "Genre"
        widget: "list"
        field: { name: "genre", label: "Genre", widget: "string" }
        default: []
        required: false

      - name: "format"
        label: "Format"
        widget: "select"
        options: ["vinyl", "digital", "cassette", "CD", "other"]
        default: "digital"

      - { name: "isDraft", label: "Draft", widget: "boolean", default: false }
      - {
          name: "isUpcoming",
          label: "Upcoming",
          widget: "boolean",
          default: false,
        }

      - {
          name: "pressKitLink",
          label: "Press Kit URL",
          widget: "string",
          required: false,
        }
      - {
          name: "recordPageLink",
          label: "Record Page URL",
          widget: "string",
          required: false,
        }

      - name: "links"
        label: "Streaming & Purchase Links"
        widget: "object"
        fields:
          - {
              name: "bandcamp",
              label: "Bandcamp",
              widget: "string",
              required: false,
            }
          - {
              name: "spotify",
              label: "Spotify",
              widget: "string",
              required: false,
            }
          - {
              name: "soundcloud",
              label: "SoundCloud",
              widget: "string",
              required: false,
            }
          - {
              name: "appleMusic",
              label: "Apple Music",
              widget: "string",
              required: false,
            }
          - {
              name: "youtube",
              label: "YouTube",
              widget: "string",
              required: false,
            }
          - { name: "tidal", label: "Tidal", widget: "string", required: false }
          - {
              name: "discogs",
              label: "Discogs",
              widget: "string",
              required: false,
            }

      - name: "tags"
        label: "Tags"
        widget: "list"
        field: { name: "tag", label: "Tag", widget: "string" }
        required: false

      - name: "relatedReleases"
        label: "Related Releases"
        widget: "relation"
        collection: "releases"
        search_fields: ["title"]
        value_field: "slug"
        display_fields: ["title"]
        multiple: true
        required: false

      - {
          name: "createdAt",
          label: "Post Created At",
          widget: "datetime",
          default: "",
          required: false,
        }
      - {
          name: "updatedAt",
          label: "Updated At",
          widget: "datetime",
          required: false,
        }

      - { name: "body", label: "Body", widget: "markdown", required: false } # Optional Markdown body

